version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:18"
  # Should be bigger than or equal to the total number of dependencies (currently 6)
  open-pull-requests-limit: 15
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: ci/dependency-updates
  labels:
    - CI/CD
