name: CD - Publish

on:
  release:
    types:
    - published

jobs:
  build:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.8.2
    if: github.repository == 'EMMC-ASBL/otelib' && startsWith(github.ref, 'refs/tags/v')
    with:
      # General settings
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      release_branch: master

      # Publish package
      python_package: true
      package_dirs: otelib
      install_extras: "[dev]"
      python_version_build: "3.9"
      build_libs: "flit"
      build_cmd: "flit build"
      publish_on_pypi: false
      upload_distribution: true
      changelog_exclude_labels: "skip-changelog,duplicate,question,invalid,wontfix"

      # Documentation
      update_docs: false
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest

    # Using environments is recommended by PyPI when using Trusted Publishers
    environment:
      name: pypi
      url: https://pypi.org/project/otelib

    # The id-token:write permission is required by the PyPI upload action for
    # Trusted Publishers
    permissions:
      id-token: write

    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: dist  # The artifact will always be called 'dist'
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
