name: CI/CD - New updates to 'master'

on:
  push:
    branches: [master]

jobs:
  update-dependabot-branch:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v1
    if: github.repository_owner == 'EMMC-ASBL'
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      permanent_dependencies_branch: ci/dependency-updates
      default_repo_branch: master
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
